language: java # 언어 java
before_install: # 패키지를 다운로드 받기 전
  - npm install -g yarn  # yarn을 글로벌로 설치
branches:
  only:
    - master
notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - despiguile@gmail.com